### ISSUE TITLE
NameError: name 'RandomAgent' is not defined

### ISSUE THREAD

**Issue by xfyecn** [nkrgit/Fleet-Scheduling-using-MADDPG-Multi-Agent-RL#1]
Hi nkrgit,

      I am very sorry to disturb you. I run the code unsuccefullly, here is some detail about that. May you help me? 
      thanks in advance.
Sincerely,
Xianfeng Ye

$py Fleet_Scheduling_Report_MADDPG.py 
/home/srv/anaconda/anaconda3/envs/rllib/lib/python3.8/site-packages/google/colab/data_table.py:30: UserWarning: IPython.utils.traitlets has moved to a top-level traitlets package.
  from IPython.utils import traitlets as _traitlets
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
Traceback (most recent call last):
  File "Fleet_Scheduling_Report_MADDPG.py", line 415, in <module>
    q_learning()
  File "Fleet_Scheduling_Report_MADDPG.py", line 213, in q_learning
    agent = RandomAgent(env)#creating a random agent to explore the given environments
NameError: name 'RandomAgent' is not defined

**Comment by nkrgit** [comment]
Hello Xianfeng, you can just remove or comment *agent =
RandomAgent(env)#creating a random agent to explore the given
environments *part.....
I have removed in my final version. Sorry for the trouble. Please use
packages with specified versions otherwise you will get into lot of errors.


*UserWarning: IPython.utils.traitlets has moved to a top-level traitlets
package.from IPython.utils import traitlets as _traitlets*

For the above case try using only CPU or only GPU for tasks

Thank You
K Naga Kiran Reddy

**Comment by nkrgit** [comment]
Made changes to the above file please use the updated file

**Comment by xfyecn** [comment]
Hi K Naga Kiran Reddy,

    Thank you so much for quick responce. That issue has been fixed. Another error arises:

Input In [83], in <cell line: 28>()
     26 # action space is a list of arrays, assume each agent has same action space
     27 n_actions = 5
---> 28 maddpg_agents = Grid_MADDPG(actor_dims, critic_dims, n_agents, n_actions, 
     29                       fc1=64, fc2=64,  
     30                       alpha=0.01, beta=0.01,
     31                       chkpt_dir='tmp/maddpg_grid/')
     33 memory = MultiAgentReplayBuffer(10000, critic_dims, actor_dims, 
     34                   n_actions, n_agents, batch_size=64)
     36 total_episodes = 500

TypeError: __init__() got an unexpected keyword argument 'chkpt_dir'

$mkdir -p   tmp/maddpg_grid/ && mkdir /tmp/maddpg_grid/
It doesn't work.

---
Xianfeng

**Comment by nkrgit** [comment]
I will check and get back to you.

**Comment by nkrgit** [comment]
I hope everything's alright now!!

**Comment by xfyecn** [comment]
Hi  K Naga Kiran Reddy, 
    It works. Thank you so so so much!

Sincerely,
Xianfeng

**Comment by nkrgit** [comment]
You're welcome!
